import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kaayamo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
      <div className="second-header">
        <div className="second-header_1 header-logo d-flex justify-content-between align-items-center ">
          <div className="logo ">
            {/* <Link href=""> */}
              {" "}
              <a>
              <Image src='/Images/favicon-32x32.png' width={40} height={40} alt="" />
              </a>
            {/* </Link> */}
          </div>
          <div className="items  ">
            <ul className=" ul-element">
              <li>
                <Link
                  href="KaayHome"
                  style={({ isActive }) =>  isActive? {color: "#fff",background: "#22577A",borderRadius:"0.2rem",fontWeight:"normal"}: { color: "black", background: "" } }
                >
                 <a> About</a>
                </Link>
              </li>
              <li>
                <Link
                  href="KaayCommunity"
                  style={({ isActive }) =>  isActive? {color: "#fff",background: "#22577A",borderRadius:"0.2rem",fontWeight:"normal"}: { color: "black", background: "" } }                >
                  <a>Our Inspiration </a>
                </Link>
              </li>
              <li>
                <Link
                  href="Gurukul"
                  style={({ isActive }) =>  isActive? {color: "#fff",background: "#22577A",borderRadius:"0.2rem",fontWeight:"normal"}: { color: "black", background: "" } }
                >
                 <a> Programs</a>
                </Link>
              </li>
               <li>
              {/* <Link
                  href="/Coursecatalog"
                  style={({ isActive }) =>  isActive? {color: "#fff",background: "#22577A",borderRadius:"0.2rem",fontWeight:"normal"}: { color: "black", background: "" } }
                >
                  Course Catalog
                </Link> */}
              </li>
            </ul>
          </div>
        </div>
        </div>
      </nav>

    </div>
  )
}
